name: Restructure Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0 * * *'  # Runs daily at midnight thirty UTC

jobs:
  restructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Directory Structure
        run: |
          # Create required directories if they don't already exist
          mkdir -p code/Python
          mkdir -p code/LaTeX
          mkdir -p whitepaper/figures
          mkdir -p docs
          mkdir -p contributions

          # Move stray .tex files from root to whitepaper/
          if ls *.tex 1> /dev/null 2>&1; then
              mv *.tex whitepaper/ || true
          fi

          # Log the directory structure for debugging purposes
          echo "Updated Directory Structure:"
          ls -R

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.PAT1 }}
        run: |
          git config --global user.email "automation@BRiidGiT.ai.git"
          git config --global user.name "BRiidGIT.ai"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated: Updated repository directory structure"
          git push https://$PAT@github.com/nuzer05ive/BRiidGiT.ai.git HEAD:main || echo "No changes to push."
