name: Setup Recursive Directory Structure

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI
  push:
    branches:
      - main  # Run when pushing to the main branch

jobs:
  setup_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Recursive Directory Structure
        run: |
          mkdir -p LL_Pairs/Verified
          mkdir -p LL_Pairs/Pending_Review
          mkdir -p LL_Pairs/Rejected
          
          mkdir -p Math_Optimizations/LaTeX
          mkdir -p Math_Optimizations/Graphical_Validations
          
          mkdir -p User_Submissions/Branches
          mkdir -p User_Submissions/Discussions
          
          mkdir -p AI_Automation
          touch AI_Automation/daily_LL_verification.py
          touch AI_Automation/notify_users.py
          
          mkdir -p Docs
          touch Docs/README.md
          touch Docs/CONTRIBUTING.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated setup of recursive directory structure"
          git push
        continue-on-error: true  # Prevent failure if no changes are made
