name: Validate Contributions

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Contribution Files
        run: |
          echo "Validating contribution files..."
          # Ensure the contributions folder exists
          if [ ! -d "contributions" ]; then
              echo "Error: contributions/ directory is missing!"
              exit 1
          fi
          # Check that all files in contributions/ have allowed extensions (.py, .tex, .md)
          for file in contributions/*; do
              if [[ "$file" != *.py && "$file" != *.tex && "$file" != *.md ]]; then
                  echo "Error: $file does not have an allowed extension (.py, .tex, or .md)"
                  exit 1
              fi
          done
          echo "All contribution files validated successfully."
